{
  "formatVersion": "1.1",
  "component": {
    "group": "org.getodk",
    "module": "javarosa",
    "version": "5.1.4-smap",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.10.13"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.33"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.77"
          }
        },
        {
          "group": "net.sf.kxml",
          "module": "kxml2",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        }
      ],
      "files": [
        {
          "name": "javarosa-5.1.4-smap.jar",
          "url": "javarosa-5.1.4-smap.jar",
          "size": 698321,
          "sha512": "d39a941ea53d9483903def7edf9b05f7a02a4b267e68e6eb6405f404adabac475a053661d90e4b7117cb41b601ebc37c2b3a9f7f30277492eb2fda77db4e93e7",
          "sha256": "d0d4e87dd923b19c7fbc205d9554bedfb1b8ee0cb34708075f972063986065c7",
          "sha1": "09bd5b2ffc32bd792910c1e9cc00bcca9006bb2f",
          "md5": "87737b14c7f087cd320429cedc9d70ff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.10.13"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.33"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.77"
          }
        },
        {
          "group": "net.sf.kxml",
          "module": "kxml2",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        }
      ],
      "files": [
        {
          "name": "javarosa-5.1.4-smap.jar",
          "url": "javarosa-5.1.4-smap.jar",
          "size": 698321,
          "sha512": "d39a941ea53d9483903def7edf9b05f7a02a4b267e68e6eb6405f404adabac475a053661d90e4b7117cb41b601ebc37c2b3a9f7f30277492eb2fda77db4e93e7",
          "sha256": "d0d4e87dd923b19c7fbc205d9554bedfb1b8ee0cb34708075f972063986065c7",
          "sha1": "09bd5b2ffc32bd792910c1e9cc00bcca9006bb2f",
          "md5": "87737b14c7f087cd320429cedc9d70ff"
        }
      ]
    }
  ]
}
