{
  "formatVersion": "1.1",
  "component": {
    "group": "org.getodk",
    "module": "javarosa",
    "version": "5.1.4-smap",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.10.13"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.33"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.77"
          }
        },
        {
          "group": "net.sf.kxml",
          "module": "kxml2",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        }
      ],
      "files": [
        {
          "name": "javarosa-5.1.4-smap.jar",
          "url": "javarosa-5.1.4-smap.jar",
          "size": 697625,
          "sha512": "511b8772a74e2b6c4ed46d6a5729db1735ee11d3eade52607b3fdae76db0330e32a5b6a6e3950320e616834bd92fa0bfbff255240751e80c0123f1b1526edb1c",
          "sha256": "7be917eecb8673398116858390f74fa9af6bda962577409463fa8d653293dad6",
          "sha1": "4d55901904b18422ff95de91a1d30148e6920d20",
          "md5": "0b851db267a44d9325995399b429b305"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.10.13"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.33"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.77"
          }
        },
        {
          "group": "net.sf.kxml",
          "module": "kxml2",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        }
      ],
      "files": [
        {
          "name": "javarosa-5.1.4-smap.jar",
          "url": "javarosa-5.1.4-smap.jar",
          "size": 697625,
          "sha512": "511b8772a74e2b6c4ed46d6a5729db1735ee11d3eade52607b3fdae76db0330e32a5b6a6e3950320e616834bd92fa0bfbff255240751e80c0123f1b1526edb1c",
          "sha256": "7be917eecb8673398116858390f74fa9af6bda962577409463fa8d653293dad6",
          "sha1": "4d55901904b18422ff95de91a1d30148e6920d20",
          "md5": "0b851db267a44d9325995399b429b305"
        }
      ]
    }
  ]
}
