{
  "formatVersion": "1.1",
  "component": {
    "group": "org.getodk",
    "module": "javarosa",
    "version": "5.1.6-smap",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.10.13"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.33"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.77"
          }
        },
        {
          "group": "net.sf.kxml",
          "module": "kxml2",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        }
      ],
      "files": [
        {
          "name": "javarosa-5.1.6-smap.jar",
          "url": "javarosa-5.1.6-smap.jar",
          "size": 698641,
          "sha512": "05c85427389abd14a8b9b3501289e4bc610f933a06f019d4cbc9796f8cdc1226039ed767fee1b39561585333459a8b1713f6d6450ab4d632d6d753ec5ec91b39",
          "sha256": "5e5105e8de05b4b79ddef58585c6fe1366887ee5d39698b3c7be40467b728230",
          "sha1": "08e77276eccbc09cf6df35d780e3a163caa89007",
          "md5": "e6abbbc217e7f38b8849c4fc6ec36b6e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.10.13"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.33"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.77"
          }
        },
        {
          "group": "net.sf.kxml",
          "module": "kxml2",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        }
      ],
      "files": [
        {
          "name": "javarosa-5.1.6-smap.jar",
          "url": "javarosa-5.1.6-smap.jar",
          "size": 698641,
          "sha512": "05c85427389abd14a8b9b3501289e4bc610f933a06f019d4cbc9796f8cdc1226039ed767fee1b39561585333459a8b1713f6d6450ab4d632d6d753ec5ec91b39",
          "sha256": "5e5105e8de05b4b79ddef58585c6fe1366887ee5d39698b3c7be40467b728230",
          "sha1": "08e77276eccbc09cf6df35d780e3a163caa89007",
          "md5": "e6abbbc217e7f38b8849c4fc6ec36b6e"
        }
      ]
    }
  ]
}
