{
  "formatVersion": "1.1",
  "component": {
    "group": "org.getodk",
    "module": "javarosa",
    "version": "6.0.0-smap",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.10.13"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.33"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.77"
          }
        },
        {
          "group": "net.sf.kxml",
          "module": "kxml2",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        }
      ],
      "files": [
        {
          "name": "javarosa-6.0.0-smap.jar",
          "url": "javarosa-6.0.0-smap.jar",
          "size": 712444,
          "sha512": "65320e0c7a6eba05e3deb598e416284d0d29cde2a7c6cab2d08559790ac197acbb18ebd6212632ddef4c316dc78ad4b170eb0806574e98c377b39b6634fd40fe",
          "sha256": "172a5e4ac5913c47e919298c3acb8b19febb58527b023d761ea07d126685b98b",
          "sha1": "e4f7025d172ec5529a3f3254c59b5b8ba574c144",
          "md5": "72df5c47020cd0f762704fc9ee37db65"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.10.13"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.33"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.77"
          }
        },
        {
          "group": "net.sf.kxml",
          "module": "kxml2",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        }
      ],
      "files": [
        {
          "name": "javarosa-6.0.0-smap.jar",
          "url": "javarosa-6.0.0-smap.jar",
          "size": 712444,
          "sha512": "65320e0c7a6eba05e3deb598e416284d0d29cde2a7c6cab2d08559790ac197acbb18ebd6212632ddef4c316dc78ad4b170eb0806574e98c377b39b6634fd40fe",
          "sha256": "172a5e4ac5913c47e919298c3acb8b19febb58527b023d761ea07d126685b98b",
          "sha1": "e4f7025d172ec5529a3f3254c59b5b8ba574c144",
          "md5": "72df5c47020cd0f762704fc9ee37db65"
        }
      ]
    }
  ]
}
